### PR TITLE
Remove play button and fix level select button asset

### PR DESCRIPTION
**Pull request by BryanGraeser**
Removed play button and also fixed an issue with level select asset -- but level select now needs to be compressed again. Also please test on iOS.

Windows: 
image

Android:
Screenshot_20210522-133904_Panic Painter

### CODE REVIEW

**Review by lsizemore8 — DISMISSED** [review]
Looks the same on iOS as it does windows/android/ If possible, maybe move settings lower so settings & level select are more spaced out? rn it looks weird cramped. if too much work don't bother though (hence the approval). I'll approve again once asset optimization occurs if need be.

**Review by foxhatleo — CHANGES_REQUESTED** [review]
Blocking this until compression is done

**Review by foxhatleo — DISMISSED** [review]
Optimized

**Comment by BryanGraeser** [comment]
Switched level select button for "play"
image

**Review by lsizemore8 — APPROVED** [review]
Play looks good on iOS

**Pull request merged**
