### PR TITLE
Background music

### PR DESCRIPTION
**Pull request by foxhatleo**
BGM is now live! I have put in a menu music as well as music for each world. Sound controller works with save controller now.

### CODE REVIEW

**Review by lsizemore8 — CHANGES_REQUESTED** [review]
Code looks great, can't break anything there. Music choice wise, when I play the space level (and the museum to an extent too), the music makes me almost not want to do the fast-paced actions required for the game cause the music is too slow-paced and calm. I can change to approve if we just want to stick with these songs for now but is this worth discussing with design about? The other music choices are 10/10 for me but regardless we should show them to design

**Comment by BryanGraeser** [comment]
Audio works on mobile, each level has a different song too and it all is working. I do agree with Laura that we should get team approval/comments on the precise songs. Especially design

**Comment by foxhatleo** [comment]
Syeyoung went through music and said they were fine

**Review by lsizemore8 — APPROVED** [review]
During Tuesday's meeting we should demo the game with the music to the team but for the sake of the submission approving this. We'll need to test this w/ assets-optimize to ensure we don't cause an iOS crash again. I tested on Walker's device and it seemed fine? but my phone had issues before Walker's device did.

**Pull request merged**
