### PR TITLE
Menu screen

### PR DESCRIPTION
**Pull request by BryanGraeser**
After much struggle, got menu screen working for the most part. Only the play button is hooked up bc there is no level or settings page yet.

I was wondering if you could give me some tips to make the buttons responsive. Rn the size & position of the buttons is not responsive I think. The button attributes are set in `assets/scenes/menu.json` (still a little messy, I'm cleaning it up). Lmk what you think.

Also still need to add the other image assets.

### CODE REVIEW

**Review by foxhatleo — DISMISSED** [review]
Looks good

**Comment by BryanGraeser** [comment]
image

Here is what it looks like now (added other textures)

**Comment by BryanGraeser** [comment]
My understanding is these new textures should be responsive, right? @foxhatleo

**Review by foxhatleo — APPROVED** [review]
Looks good

**Pull request merged**
