### PR TITLE
cross-level color order consistency

### PR DESCRIPTION
**Pull request by AnshG714**
Implement same color orders across levels.

### CODE REVIEW

**Comment by AnshG714** [comment]
This PR also makes a small asset fix (nothing big to review here)

**Review by BryanGraeser — DISMISSED** [review]
Looks good. Is there a way to make this change to the level editor to ensure we don't have to manually edit new JSONs in the future? Or is that more work than just editing JSONs?

**Comment by AnshG714** [comment]
Nope, we should be able to change the level generator easily for that. Just don't know if we're going to use that generator now.

**Review by BryanGraeser — APPROVED** [review]
Re-Approved

**Pull request merged**
