### PR TITLE
Rhs palette

### PR DESCRIPTION
**Pull request by AnshG714**
This PR implements the RHS palette. For some reason, there were MANY positioning issues on Desktop vs. mobile, so i had to do some wacky stuff to get it to work. pls review quickly.

### CODE REVIEW

**Review by BryanGraeser — CHANGES_REQUESTED** [review]
Does not work on android mobile. Built with android studio. Correctly showed up on left side, but this is what it looks like on the right side: 
Screenshot_20210517-122924_Panic Painter

Additionally, did not build on visual studio, got these errors: 
image

I'm trying to look into why but haven't found it yet

**Comment by BryanGraeser** [comment]
Sorry for the delay

**Comment by AnshG714** [comment]
FYI for other reviewers: resolving issues via Slack

**Review by BryanGraeser — DISMISSED** [review]
tested on windows and android

**Review by BryanGraeser — APPROVED** [review]
I trust

**Pull request merged**
