### PR TITLE
Level integration

### PR DESCRIPTION
**Pull request by BryanGraeser**
Integrates house and island levels. (Eiffel level assets are also uploaded - just waiting on background)

### CODE REVIEW

**Comment by BryanGraeser** [comment]
Error on windows (strangely enough everything worked on Android): 
image

Any ideas what this means?

**Comment by BryanGraeser** [comment]
My guess is something to do with more colors on this level

**Comment by lsizemore8** [comment]
> My guess is something to do with more colors on this level

hello the issue is likely the fact that obstacles aren't integrated

**Comment by BryanGraeser** [comment]
> > My guess is something to do with more colors on this level
> 
> hello the issue is likely the fact that obstacles aren't integrated

why tf does it work on mobile then?

**Comment by BryanGraeser** [comment]
Are obstacles randomly put in only sometimes?

**Comment by lsizemore8** [comment]
> Are obstacles randomly put in only sometimes?

Oh interesting no. For beach and city I believe they all had at least one obstacle

**Comment by lsizemore8** [comment]
> > Are obstacles randomly put in only sometimes?
> 
> Oh interesting no. For beach and city I believe they all had at least one obstacle



> > > My guess is something to do with more colors on this level
> > 
> > 
> > hello the issue is likely the fact that obstacles aren't integrated
> 
> why tf does it work on mobile then?

I have absolutely no idea. Which level caused the assert error? I can put that one into the obstacles branch to see if it works there

**Review by lsizemore8 — APPROVED** [review]
All of the levels seem fine but for some reason beach-5 defaults to color blind mode? Not sure what's happening there

**Comment by BryanGraeser** [comment]
that is a very weird bug -- will look into later

**Pull request merged**
